language: rust
rust:
  - 1.17.0
python:
  - "2.7"
install:
  - wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  - tar -xvf emsdk-portable.tar.gz
  - ./emsdk update
  - ./emsdk install latest
  - ./emsdk activate latest
cache:
  - cargo
before_script:
  - rustup target add wasm32-unknown-emscripten
script: make release
