language: rust
dist: trusty
rust:
  - 1.17.0
python:
  - "2.7"
install:
  - wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  - tar -xf emsdk-portable.tar.gz
  - ./emsdk-portable/emsdk update
  - ./emsdk-portable/emsdk install latest | tail
  - ./emsdk-portable/emsdk activate latest
  - source emsdk-portable/emsdk_env.sh
  - git clone https://github.com/WebAssembly/binaryen
  - cd binaryen
  - cmake . && make
  - cd -
  - echo "BINARYEN_ROOT='`pwd`/binaryen'" | tee ~/.emscripten
cache:
  - cargo
before_script:
  - rustup target add wasm32-unknown-emscripten
script: RUST_BACKTRACE=1 make release
