language: rust
rust:
  - 1.17.0
python:
  - "2.7"
before_install:
  - export CC=gcc-5
  - export CXX=g++-5
install:
  - wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  - tar -xf emsdk-portable.tar.gz
  - ./emsdk-portable/emsdk update
  - ./emsdk-portable/emsdk install latest
  - ./emsdk-portable/emsdk activate latest
  - source emsdk-portable/emsdk_env.sh
  - git clone https://github.com/WebAssembly/binaryen
  - cd binaryen
  - cmake . && make
  - cd -
  - echo "`pwd`/binaryen" | tee ~/.emscripten
cache:
  - cargo
before_script:
  - rustup target add wasm32-unknown-emscripten
script: make release
